=== SenpaiSumpie/awesome-lists/scripts/data/schema/list-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "item": {
      "type": "object",
      "properties": {
        "name": { "type": "string" },
        "link": {
          "type": "string",
          "format": "uri"
        },
        "description": { "type": "string" }
      },
      "required": ["name", "description"]
    },
    "category": {
      "type": "object",
      "properties": {
        "name": { "type": "string" },
        "items": {
          "type": "array",
          "items": { "$ref": "#/definitions/item" }
        }
      },
      "required": ["name", "items"]
    }
  },
  "type": "object",
  "properties": {
    "title": {
      "type": "string"
    },
    "fileName": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "date": {
      "type": "string",
      "format": "date-time"
    },
    "categories": {
      "type": "array",
      "items": { "$ref": "#/definitions/category" }
    }
  },
  "required": ["title", "fileName", "description", "date", "categories"]
}

=== SenpaiSumpie/awesome-lists/lists/vs-code/vs-code.hbs.json
{
  "$schema": "../../scripts/data/schema/list-schema.json",
  "title": "VSCode Extensions",
  "fileName": "vs-code",
  "description": "This is a curated list of the awesome must-use extensions for VS Code!",
  "date": "2023-12-12T23:08:50.346Z",
  "categories": [
    {
      "name": "Quality of Life Extensions",
      "items": [
        {
          "name": "Auto Close Tag",
          "link": "https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-close-tag",
          "description": "Automatically add HTML/XML close tag."
        }
      ]
    },
    {
      "name": "Themes, Icons and Graphical Extensions",
      "items": [
        {
          "name": "Peacock",
          "link": "https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock",
          "description": "Distinguish between multiple VS Code Instances Easier."
        }
      ]
    },
    {
      "name": "Testing / Debugging Extensions",
      "items": [
        {
          "name": "Error Lens",
          "link": "https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens",
          "description": "ErrorLens turbo-charges language diagnostic features by making diagnostics stand out more."
        }
      ]
    }
  ]
}

=== SenpaiSumpie/awesome-lists/lists/node-packages/node-packages.hbs.json
{
  "$schema": "../../scripts/data/schema/list-schema.json",
  "title": "Node Packages",
  "fileName": "node-packages",
  "description": "A list of awesome Web Dev, tools, frameworks, and extensions to make life easier!",
  "date": "2023-12-12T23:08:29.464Z",
  "categories": [
    {
      "name": "React",
      "items": []
    },
    {
      "name": "Next JS",
      "items": [
        {
          "name": "Next Cache Explorer",
          "link": "https://github.com/47ng/next-cache-explorer",
          "description": "Navigate & debug the Next.js data cache"
        },
        {
          "name": "Some Next Package",
          "link": "https://github.com",
          "description": "Something somethings i dont know"
        }
      ]
    },
    {
      "name": "TypeScript",
      "items": [
        {
          "name": "TS Pattern",
          "link": "https://github.com/gvergnaud/ts-pattern",
          "description": "The exhaustive Pattern Matching library for TypeScript with smart type inference."
        }
      ]
    },
    {
      "name": "Miscellaneous",
      "items": []
    }
  ]
}
